### ISSUE TITLE
re: get_account_blocks()

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [schochastics/rtoot#66]
Hi rtoot !

I am curious if you are open to the idea of changing the name of `get_account_blocks()` to `blocked_users()` as I was unsure what account blocks was. Silly perhaps to not understand that right away, but I understood after I saw the 1 account I have blocked  show up as the result, and then it made sense. 

Anyway, thanks for this package. 😄

**Comment by schochastics** [comment]
I personally wouldnt want to change it because I prefer to have a consistent API. all account level actions start with `get_account_`. We would also have to change `get_account_mutes` to `muted_users` etc. I am happy to be convinced otherwise if others feel that our naming isnt good, but for now, I'd like to leave it as is
